name: Scrape & Publish

on:
  schedule:
    - cron: "0 * * * *"   # la fix de oră (UTC) -> ~ora +2 la Viena în UI
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -r requirements.txt
      - name: Run scraper
        run: python scraper/scraper.py
      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add web/data/merged.json web/data/reload.log
          git commit -m "data: update $(Get-Date -Format 'yyyy-MM-dd HH:mm')" || echo "no changes"
          git push
      - name: Deploy to Pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          publish_branch: gh-pages
